#14-Regarding the Back End-DelroyGayle
berkeli/breteau-dashboard pull request #19
Opened 2022-07-18 15:52 UTC by DelroyGayle

## #14-Regarding the Back End-DelroyGayle

## Description
Created the schemas and mock data for 5 databases

1. User
2. Initiative
3. Programme
4. SchoolStats
5. SchoolSurveys

## Related to
#14

Reviewers please check that I have not missed a field

I could not remember the different types of users that we decided so I went with

Super Admin, Country Manager and General User

Of course, everything is subject to change so please point out the correct titles.
Thank you

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have carefully reviewed my own code
- [x] I have commented my code
- [x] I have updated any documentation

2022-07-18 18:47 UTC, berkeli commented on server/db/initiatives-migration.sql
> +   updatedAt TIMESTAMP NOT NULL DEFAULT NOW()
I don't think we need updated by, if we are adding updated by then we need to add the relevant reference
```suggestion
   updatedById INT NOT NULL,
   updatedAt TIMESTAMP NOT NULL DEFAULT NOW()
   FOREIGN KEY (updatedById) REFERENCES users (id)
   FOREIGN KEY (createdById) REFERENCES users (id)
```

2022-07-18 18:48 UTC, berkeli commented on server/db/programme-migration.sql
> +CREATE TABLE programme (
programme and initiative are both the same

2022-07-18 18:49 UTC, berkeli commented on server/db/user-migration.sql
> +CREATE TABLE users (
we should follow same naming scheme, i.e. not plural (programme, initiative, user)
```suggestion
CREATE TABLE user (
```

2022-07-18 18:50 UTC, berkeli commented on server/db/user-migration.sql
> +   userName VARCHAR(50) NOT NULL,
We will not be using usernames, only email + password for login

2022-07-18 18:51 UTC, berkeli commented on server/db/user-migration.sql
> +   updatedAt TIMESTAMP NOT NULL DEFAULT NOW()
I don't think we need this information on user
instead we can add the country of the user
```suggestion
 country VARCHAR(50) NOT NULL
```

2022-07-18 18:53 UTC, berkeli commented on server/routes/api.js
> +});
Please note the users endpoint has already been implemented and we get users from auth0. I'm not sure why you are working on users endpoints

2022-07-18 18:54 UTC, berkeli requested changes
Thanks @DelroyGayle Looks good, but please remove users endpoints as they are already implemented and your code is overriding what I have implemented for the users endpoint.

2022-07-18 18:58 UTC, berkeli commented
Also, there's one more table missing - ScheduleTracker
It should have the following fields

Programme/Initiative  -> reference to programme
School/NGO name -> reference to school
No. of new students reached - number
No. of existing students reached - number
No. of new teachers reached- number
No. of existing students reached - number
No. of tablets (if applicable)- number
Grades - text (for now, at least 255 chars )
Languages Taught - text (for now, at least 255 chars )
createdById -> -> reference to user

2022-07-19 10:12 UTC, DelroyGayle commented
> please remove users endpoints as they are already implemented and your code is overriding what I have implemented for the users endpoint.

2022-07-19 10:12 UTC, closed without merging